#!/bin/bash

# Extended glob pattern: !(*.ejs)
shopt -s extglob
# When no file matches glob, don't treat the pattern as literal string
shopt -s nullglob

#commit_hash=`git rev-parse --short HEAD`
commit_hash=`tr -dc A-Za-z0-9 </dev/urandom | head -c 13; echo`

for dir in ./src/notetypes/*/ ; do
    NOTETYPE_DIR="./Note Types/$(basename "${dir}")"
    
    for file in "${NOTETYPE_DIR}"/* ; do
        rm "$file"
    done

    front_file="${NOTETYPE_DIR}/Front Template.html"
    back_file="${NOTETYPE_DIR}/Back Template.html"

    npx ejs "$dir"/front.ejs -o "$front_file"
    npx ejs "$dir"/back.ejs -o "$back_file"

    echo "<!-- version ${commit_hash} -->" | cat - "${front_file}" > /tmp/out && mv /tmp/out "${front_file}"
    echo "<!-- version ${commit_hash} -->" | cat - "${back_file}" > /tmp/out && mv /tmp/out "${back_file}"

    for file in "${dir}"!(*.ejs) ; do
        cp "$file" "${NOTETYPE_DIR}/$(basename "$file")"
    done
done
